/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;
import Calculos.Calculos;
import data.CadastroDao;
import data.Jogador;
import javax.swing.JOptionPane;
/**
 *
 * @author gabri
 */
public class ConsultaGoleiro extends javax.swing.JFrame {
 Calculos calc = new Calculos();
    /**
     * Creates new form ConsultaGoleiro
     */
    public ConsultaGoleiro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblNome1 = new javax.swing.JLabel();
        txtPosicao = new javax.swing.JTextField();
        lblNome2 = new javax.swing.JLabel();
        txtNumCamisa = new javax.swing.JTextField();
        btnVoltar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        lblReflexo = new javax.swing.JLabel();
        txtReflexos = new javax.swing.JTextField();
        lblPosicionamento = new javax.swing.JLabel();
        txtPosicionamento = new javax.swing.JTextField();
        lblChute = new javax.swing.JLabel();
        txtChute = new javax.swing.JTextField();
        lblFalta = new javax.swing.JLabel();
        txtCobrFalta = new javax.swing.JTextField();
        lblPenalti = new javax.swing.JLabel();
        txtCobrPenalti = new javax.swing.JTextField();
        lblPontuacao = new javax.swing.JLabel();
        txtMedia = new javax.swing.JTextField();
        btnMostrarPontuacao = new javax.swing.JButton();
        txtLimpar = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lblNome.setText("Nome");
        getContentPane().add(lblNome);
        lblNome.setBounds(10, 50, 50, 30);

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        getContentPane().add(txtNome);
        txtNome.setBounds(60, 50, 170, 30);

        lblNome1.setText("Posição");
        getContentPane().add(lblNome1);
        lblNome1.setBounds(330, 250, 50, 30);

        txtPosicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPosicaoActionPerformed(evt);
            }
        });
        getContentPane().add(txtPosicao);
        txtPosicao.setBounds(380, 250, 130, 30);

        lblNome2.setText("Nº da Camisa");
        getContentPane().add(lblNome2);
        lblNome2.setBounds(20, 90, 100, 30);

        txtNumCamisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumCamisaActionPerformed(evt);
            }
        });
        getContentPane().add(txtNumCamisa);
        txtNumCamisa.setBounds(100, 90, 130, 30);

        btnVoltar.setBackground(new java.awt.Color(255, 153, 153));
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar);
        btnVoltar.setBounds(30, 10, 90, 30);

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultar);
        btnConsultar.setBounds(10, 290, 100, 50);

        btnExcluir.setBackground(new java.awt.Color(51, 255, 204));
        btnExcluir.setText("Excluir Goleiro");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir);
        btnExcluir.setBounds(440, 10, 110, 23);

        lblReflexo.setText("Reflexo");
        getContentPane().add(lblReflexo);
        lblReflexo.setBounds(330, 90, 80, 30);

        txtReflexos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReflexosActionPerformed(evt);
            }
        });
        getContentPane().add(txtReflexos);
        txtReflexos.setBounds(420, 90, 90, 30);

        lblPosicionamento.setText("Posicionamento");
        getContentPane().add(lblPosicionamento);
        lblPosicionamento.setBounds(310, 50, 100, 30);

        txtPosicionamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPosicionamentoActionPerformed(evt);
            }
        });
        getContentPane().add(txtPosicionamento);
        txtPosicionamento.setBounds(420, 50, 90, 30);

        lblChute.setText("Chute");
        getContentPane().add(lblChute);
        lblChute.setBounds(330, 130, 80, 30);

        txtChute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChuteActionPerformed(evt);
            }
        });
        getContentPane().add(txtChute);
        txtChute.setBounds(420, 130, 90, 30);

        lblFalta.setText("Falta");
        getContentPane().add(lblFalta);
        lblFalta.setBounds(330, 170, 80, 30);

        txtCobrFalta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCobrFaltaActionPerformed(evt);
            }
        });
        getContentPane().add(txtCobrFalta);
        txtCobrFalta.setBounds(420, 170, 90, 30);

        lblPenalti.setText("Penalti");
        getContentPane().add(lblPenalti);
        lblPenalti.setBounds(330, 210, 80, 30);

        txtCobrPenalti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCobrPenaltiActionPerformed(evt);
            }
        });
        getContentPane().add(txtCobrPenalti);
        txtCobrPenalti.setBounds(420, 210, 90, 30);

        lblPontuacao.setText("Média");
        getContentPane().add(lblPontuacao);
        lblPontuacao.setBounds(330, 290, 80, 30);

        txtMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMediaActionPerformed(evt);
            }
        });
        getContentPane().add(txtMedia);
        txtMedia.setBounds(380, 290, 60, 30);

        btnMostrarPontuacao.setText("Mostrar pontuação");
        btnMostrarPontuacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarPontuacaoActionPerformed(evt);
            }
        });
        getContentPane().add(btnMostrarPontuacao);
        btnMostrarPontuacao.setBounds(450, 290, 130, 30);

        txtLimpar.setBackground(new java.awt.Color(102, 204, 255));
        txtLimpar.setText("Nova consulta");
        txtLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLimparActionPerformed(evt);
            }
        });
        getContentPane().add(txtLimpar);
        txtLimpar.setBounds(120, 300, 130, 30);

        setSize(new java.awt.Dimension(605, 422));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtPosicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPosicaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPosicaoActionPerformed

    private void txtNumCamisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumCamisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumCamisaActionPerformed

    private void txtReflexosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReflexosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReflexosActionPerformed

    private void txtPosicionamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPosicionamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPosicionamentoActionPerformed

    private void txtChuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChuteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChuteActionPerformed

    private void txtCobrFaltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCobrFaltaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCobrFaltaActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnMostrarPontuacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarPontuacaoActionPerformed
       
        if(txtPosicionamento.getText().isEmpty()){
          txtPosicionamento.setText("0");
      }if(txtCobrFalta.getText().isEmpty()){
          txtCobrFalta.setText("0");
      }if(txtCobrPenalti.getText().isEmpty()){
          txtCobrPenalti.setText("0");
      }if(txtReflexos.getText().isEmpty()){
          txtReflexos.setText("0");
      }if(txtChute.getText().isEmpty()){
          txtChute.setText("0");
      }
        calc.setFinalizacao(Byte.parseByte(txtPosicionamento.getText()));
        calc.setDefesa(Byte.parseByte(txtReflexos.getText()));
        calc.setRitmo(Byte.parseByte(txtChute.getText()));
        calc.setCobrFalta(Byte.parseByte(txtCobrFalta.getText()));
        calc.setCobrPenalti(Byte.parseByte(txtCobrPenalti.getText()));
        calc.goleiro(Float.parseFloat(txtPosicionamento.getText()), Float.parseFloat(txtReflexos.getText()), Float.parseFloat(txtChute.getText()),Float.parseFloat(txtCobrPenalti.getText()), Float.parseFloat(txtCobrFalta.getText()));
        txtMedia.setText(calc.getMedia());
    }//GEN-LAST:event_btnMostrarPontuacaoActionPerformed

    private void txtMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMediaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMediaActionPerformed

    private void txtCobrPenaltiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCobrPenaltiActionPerformed
         if(txtPosicionamento.getText().isEmpty()){
          txtPosicionamento.setText("0");
      }if(txtCobrFalta.getText().isEmpty()){
          txtCobrFalta.setText("0");
      }if(txtCobrPenalti.getText().isEmpty()){
          txtCobrPenalti.setText("0");
      }if(txtReflexos.getText().isEmpty()){
          txtReflexos.setText("0");
      }if(txtChute.getText().isEmpty()){
          txtChute.setText("0");
      }
        calc.setFinalizacao(Byte.parseByte(txtPosicionamento.getText()));
        calc.setDefesa(Byte.parseByte(txtReflexos.getText()));
        calc.setRitmo(Byte.parseByte(txtChute.getText()));
        calc.setCobrFalta(Byte.parseByte(txtCobrFalta.getText()));
        calc.setCobrPenalti(Byte.parseByte(txtCobrPenalti.getText()));
        calc.goleiro(Float.parseFloat(txtPosicionamento.getText()), Float.parseFloat(txtReflexos.getText()), Float.parseFloat(txtChute.getText()),Float.parseFloat(txtCobrPenalti.getText()), Float.parseFloat(txtCobrFalta.getText()));
        txtMedia.setText(calc.getMedia());
    }//GEN-LAST:event_txtCobrPenaltiActionPerformed

    private void txtLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLimparActionPerformed
       txtNome.setText("");
      txtNumCamisa.setText("");
      txtPosicionamento.setText("");
      txtReflexos.setText("");
      txtChute.setText("");
      txtCobrFalta.setText("");
      txtCobrPenalti.setText("");
      txtMedia.setText("");
    }//GEN-LAST:event_txtLimparActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
          new Consulta2().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
                     CadastroDao dao = new CadastroDao();
        boolean status = dao.conectar();
        if (status == true) {
            Jogador jogador = dao.consultar(txtNome.getText(), txtNumCamisa.getText());
            if (jogador==null) {
                JOptionPane.showMessageDialog(null, "O jogador não está cadastrado!");
            } else {
                txtReflexos.setText(String.valueOf(jogador.getReflexo()));
                txtChute.setText(String.valueOf(jogador.getChute()));
                txtPosicionamento.setText(jogador.getPosicionamento());
                txtCobrFalta.setText(String.valueOf(jogador.getCobrFalta()));
                txtCobrPenalti.setText(String.valueOf(jogador.getCobrPenalti()));     
                txtPosicao.setText(jogador.getPosicao()); 
            }

        } else {
            JOptionPane.showMessageDialog(null, "Erro na conexão");
        }
        
    }//GEN-LAST:event_btnConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaGoleiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaGoleiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaGoleiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaGoleiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaGoleiro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnMostrarPontuacao;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel lblChute;
    private javax.swing.JLabel lblFalta;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNome1;
    private javax.swing.JLabel lblNome2;
    private javax.swing.JLabel lblPenalti;
    private javax.swing.JLabel lblPontuacao;
    private javax.swing.JLabel lblPosicionamento;
    private javax.swing.JLabel lblReflexo;
    private javax.swing.JTextField txtChute;
    private javax.swing.JTextField txtCobrFalta;
    private javax.swing.JTextField txtCobrPenalti;
    private javax.swing.JButton txtLimpar;
    private javax.swing.JTextField txtMedia;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumCamisa;
    private javax.swing.JTextField txtPosicao;
    private javax.swing.JTextField txtPosicionamento;
    private javax.swing.JTextField txtReflexos;
    // End of variables declaration//GEN-END:variables
}
