/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import data.Jogador;

/**
 *
 * @author android-8c10
 */
public class positionSelector extends javax.swing.JFrame {
   Jogador jogador = new Jogador();
    
    /**
     * Creates new form selectionPosition
     */
    public positionSelector() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGoleiro = new javax.swing.JButton();
        btnLatDir = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        btnZagueiro2 = new javax.swing.JButton();
        btnZagueiro1 = new javax.swing.JButton();
        btnLatEsq = new javax.swing.JButton();
        btnVolante = new javax.swing.JButton();
        btnMeioCampo2 = new javax.swing.JButton();
        btnMeioCampo1 = new javax.swing.JButton();
        btnPontDir = new javax.swing.JButton();
        btnAtacante3 = new javax.swing.JButton();
        btnPontEsq = new javax.swing.JButton();
        jlbChoose = new javax.swing.JLabel();
        jlbChoose2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        btnGoleiro.setBackground(new java.awt.Color(255, 153, 51));
        btnGoleiro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnGoleiro.setText("Goleiro");
        btnGoleiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoleiroActionPerformed(evt);
            }
        });
        btnGoleiro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnGoleiroKeyPressed(evt);
            }
        });
        getContentPane().add(btnGoleiro);
        btnGoleiro.setBounds(250, 590, 120, 40);

        btnLatDir.setBackground(new java.awt.Color(204, 204, 255));
        btnLatDir.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnLatDir.setText("Lateral Direito");
        btnLatDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLatDirActionPerformed(evt);
            }
        });
        btnLatDir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnLatDirKeyPressed(evt);
            }
        });
        getContentPane().add(btnLatDir);
        btnLatDir.setBounds(420, 460, 150, 40);

        btnVoltar.setBackground(new java.awt.Color(255, 153, 153));
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        btnVoltar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnVoltarKeyPressed(evt);
            }
        });
        getContentPane().add(btnVoltar);
        btnVoltar.setBounds(20, 20, 70, 48);

        btnZagueiro2.setBackground(new java.awt.Color(204, 204, 255));
        btnZagueiro2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnZagueiro2.setText("Zagueiro");
        btnZagueiro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZagueiro2ActionPerformed(evt);
            }
        });
        btnZagueiro2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnZagueiro2KeyPressed(evt);
            }
        });
        getContentPane().add(btnZagueiro2);
        btnZagueiro2.setBounds(310, 480, 100, 40);

        btnZagueiro1.setBackground(new java.awt.Color(204, 204, 255));
        btnZagueiro1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnZagueiro1.setText("Zagueiro");
        btnZagueiro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZagueiro1ActionPerformed(evt);
            }
        });
        btnZagueiro1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnZagueiro1KeyPressed(evt);
            }
        });
        getContentPane().add(btnZagueiro1);
        btnZagueiro1.setBounds(199, 480, 100, 40);

        btnLatEsq.setBackground(new java.awt.Color(204, 204, 255));
        btnLatEsq.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnLatEsq.setText("Lateral Esquerdo");
        btnLatEsq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLatEsqActionPerformed(evt);
            }
        });
        btnLatEsq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnLatEsqKeyPressed(evt);
            }
        });
        getContentPane().add(btnLatEsq);
        btnLatEsq.setBounds(31, 460, 160, 40);

        btnVolante.setBackground(new java.awt.Color(153, 255, 153));
        btnVolante.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnVolante.setText("Volante");
        btnVolante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolanteActionPerformed(evt);
            }
        });
        btnVolante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnVolanteKeyPressed(evt);
            }
        });
        getContentPane().add(btnVolante);
        btnVolante.setBounds(260, 360, 100, 40);

        btnMeioCampo2.setBackground(new java.awt.Color(153, 255, 153));
        btnMeioCampo2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnMeioCampo2.setText("Meio-Campo");
        btnMeioCampo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMeioCampo2ActionPerformed(evt);
            }
        });
        btnMeioCampo2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnMeioCampo2KeyPressed(evt);
            }
        });
        getContentPane().add(btnMeioCampo2);
        btnMeioCampo2.setBounds(320, 250, 130, 40);

        btnMeioCampo1.setBackground(new java.awt.Color(153, 255, 153));
        btnMeioCampo1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnMeioCampo1.setText("Meio-Campo");
        btnMeioCampo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMeioCampo1ActionPerformed(evt);
            }
        });
        btnMeioCampo1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnMeioCampo1KeyPressed(evt);
            }
        });
        getContentPane().add(btnMeioCampo1);
        btnMeioCampo1.setBounds(170, 250, 130, 40);

        btnPontDir.setBackground(new java.awt.Color(255, 102, 102));
        btnPontDir.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnPontDir.setText("Ponta Direita");
        btnPontDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPontDirActionPerformed(evt);
            }
        });
        btnPontDir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPontDirKeyPressed(evt);
            }
        });
        getContentPane().add(btnPontDir);
        btnPontDir.setBounds(400, 130, 140, 40);

        btnAtacante3.setBackground(new java.awt.Color(255, 102, 102));
        btnAtacante3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnAtacante3.setText("Atacante");
        btnAtacante3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtacante3ActionPerformed(evt);
            }
        });
        btnAtacante3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnAtacante3KeyPressed(evt);
            }
        });
        getContentPane().add(btnAtacante3);
        btnAtacante3.setBounds(270, 100, 89, 40);

        btnPontEsq.setBackground(new java.awt.Color(255, 102, 102));
        btnPontEsq.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnPontEsq.setText("Ponta Esquerda");
        btnPontEsq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPontEsqActionPerformed(evt);
            }
        });
        btnPontEsq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPontEsqKeyPressed(evt);
            }
        });
        getContentPane().add(btnPontEsq);
        btnPontEsq.setBounds(50, 130, 160, 40);

        jlbChoose.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jlbChoose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/kisspng-royalty-free-football-pitch-illustration-football-field-5a83a1f93fd3b5.5574839015185761212614 (2).jpg"))); // NOI18N
        getContentPane().add(jlbChoose);
        jlbChoose.setBounds(90, 50, 440, 610);

        jlbChoose2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jlbChoose2.setText("Escolha a posição do jogador a ser cadastrado");
        getContentPane().add(jlbChoose2);
        jlbChoose2.setBounds(120, 10, 440, 30);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setOpaque(false);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 610, 660);

        setSize(new java.awt.Dimension(618, 694));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        new TelaPrincipal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnMeioCampo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMeioCampo2ActionPerformed
        new MeioCampo().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMeioCampo2ActionPerformed

    private void btnZagueiro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZagueiro2ActionPerformed
        new Zagueiro().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnZagueiro2ActionPerformed

    private void btnZagueiro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZagueiro1ActionPerformed
        new Zagueiro().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnZagueiro1ActionPerformed

    private void btnLatDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLatDirActionPerformed
        new LateralDireito().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLatDirActionPerformed

    private void btnLatEsqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLatEsqActionPerformed
        new LateralEsquerdo().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLatEsqActionPerformed

    private void btnGoleiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoleiroActionPerformed
        new Goleiro().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGoleiroActionPerformed

    private void btnVolanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolanteActionPerformed
        new Volante().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolanteActionPerformed

    private void btnAtacante3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtacante3ActionPerformed
        new Atacante().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAtacante3ActionPerformed

    private void btnMeioCampo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMeioCampo1ActionPerformed
        new MeioCampo().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMeioCampo1ActionPerformed

    private void btnPontDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPontDirActionPerformed
        new PontaDireita().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPontDirActionPerformed

    private void btnPontEsqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPontEsqActionPerformed

        new PontaEsquerda().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPontEsqActionPerformed

    private void btnAtacante3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAtacante3KeyPressed
        // TODO add your handling code here:
        new Atacante().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAtacante3KeyPressed

    private void btnPontDirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnPontDirKeyPressed
        // TODO add your handling code here:
        new PontaDireita().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPontDirKeyPressed

    private void btnPontEsqKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnPontEsqKeyPressed
        // TODO add your handling code here:
        new PontaEsquerda().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPontEsqKeyPressed

    private void btnMeioCampo1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnMeioCampo1KeyPressed
        // TODO add your handling code here:
        new MeioCampo().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMeioCampo1KeyPressed

    private void btnMeioCampo2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnMeioCampo2KeyPressed
        // TODO add your handling code here:
        new MeioCampo().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMeioCampo2KeyPressed

    private void btnVolanteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnVolanteKeyPressed
        // TODO add your handling code here:
         new Volante().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolanteKeyPressed

    private void btnLatEsqKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnLatEsqKeyPressed
        // TODO add your handling code here:
        new LateralEsquerdo().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLatEsqKeyPressed

    private void btnLatDirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnLatDirKeyPressed
        // TODO add your handling code here:
        new LateralDireito().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLatDirKeyPressed

    private void btnZagueiro1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnZagueiro1KeyPressed
        // TODO add your handling code here:
         new Zagueiro().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnZagueiro1KeyPressed

    private void btnZagueiro2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnZagueiro2KeyPressed
        // TODO add your handling code here:
         new Zagueiro().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnZagueiro2KeyPressed

    private void btnGoleiroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnGoleiroKeyPressed
        // TODO add your handling code here:
        new Goleiro().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGoleiroKeyPressed

    private void btnVoltarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnVoltarKeyPressed
        // TODO add your handling code here:
        new TelaPrincipal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(positionSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(positionSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(positionSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(positionSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new positionSelector().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtacante3;
    private javax.swing.JButton btnGoleiro;
    private javax.swing.JButton btnLatDir;
    private javax.swing.JButton btnLatEsq;
    private javax.swing.JButton btnMeioCampo1;
    private javax.swing.JButton btnMeioCampo2;
    private javax.swing.JButton btnPontDir;
    private javax.swing.JButton btnPontEsq;
    private javax.swing.JButton btnVolante;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JButton btnZagueiro1;
    private javax.swing.JButton btnZagueiro2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlbChoose;
    private javax.swing.JLabel jlbChoose2;
    // End of variables declaration//GEN-END:variables
}
