
package view;

public class selectionPosition extends javax.swing.JFrame {

    /**
     * Creates new form selectionPosition
     */
    public selectionPosition() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAtacante6 = new javax.swing.JButton();
        jlbChoose = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnPontEsq = new javax.swing.JButton();
        btnPontDir = new javax.swing.JButton();
        btnMeioCampo1 = new javax.swing.JButton();
        btnAtacante3 = new javax.swing.JButton();
        btnVolante = new javax.swing.JButton();
        btnGoleiro = new javax.swing.JButton();
        btnLatEsq = new javax.swing.JButton();
        btnLatDir = new javax.swing.JButton();
        btnZagueiro1 = new javax.swing.JButton();
        btnZagueiro2 = new javax.swing.JButton();
        btnMeioCampo2 = new javax.swing.JButton();

        btnAtacante6.setBackground(new java.awt.Color(153, 255, 153));
        btnAtacante6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnAtacante6.setText("Atacante");
        btnAtacante6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtacante6ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlbChoose.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jlbChoose.setText("Escolha a posição do jogador a ser cadastrado");

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));

        btnPontEsq.setBackground(new java.awt.Color(255, 102, 102));
        btnPontEsq.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnPontEsq.setText("Ponta Esquerda");
        btnPontEsq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPontEsqActionPerformed(evt);
            }
        });

        btnPontDir.setBackground(new java.awt.Color(255, 102, 102));
        btnPontDir.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnPontDir.setText("Ponta Direita");
        btnPontDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPontDirActionPerformed(evt);
            }
        });

        btnMeioCampo1.setBackground(new java.awt.Color(153, 255, 153));
        btnMeioCampo1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnMeioCampo1.setText("Meio-Campo");
        btnMeioCampo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMeioCampo1ActionPerformed(evt);
            }
        });

        btnAtacante3.setBackground(new java.awt.Color(255, 102, 102));
        btnAtacante3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnAtacante3.setText("Atacante");
        btnAtacante3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtacante3ActionPerformed(evt);
            }
        });

        btnVolante.setBackground(new java.awt.Color(153, 255, 153));
        btnVolante.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnVolante.setText("Volante");
        btnVolante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolanteActionPerformed(evt);
            }
        });

        btnGoleiro.setBackground(new java.awt.Color(255, 153, 51));
        btnGoleiro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnGoleiro.setText("Goleiro");
        btnGoleiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoleiroActionPerformed(evt);
            }
        });

        btnLatEsq.setBackground(new java.awt.Color(204, 204, 255));
        btnLatEsq.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnLatEsq.setText("Lateral Esquerdo");
        btnLatEsq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLatEsqActionPerformed(evt);
            }
        });

        btnLatDir.setBackground(new java.awt.Color(204, 204, 255));
        btnLatDir.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnLatDir.setText("Lateral Direito");
        btnLatDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLatDirActionPerformed(evt);
            }
        });

        btnZagueiro1.setBackground(new java.awt.Color(204, 204, 255));
        btnZagueiro1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnZagueiro1.setText("Zagueiro");
        btnZagueiro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZagueiro1ActionPerformed(evt);
            }
        });

        btnZagueiro2.setBackground(new java.awt.Color(204, 204, 255));
        btnZagueiro2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnZagueiro2.setText("Zagueiro");
        btnZagueiro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZagueiro2ActionPerformed(evt);
            }
        });

        btnMeioCampo2.setBackground(new java.awt.Color(153, 255, 153));
        btnMeioCampo2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnMeioCampo2.setText("Meio-Campo");
        btnMeioCampo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMeioCampo2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnLatEsq)
                                .addGap(66, 66, 66)
                                .addComponent(btnZagueiro1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnMeioCampo1)
                                .addGap(125, 125, 125)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMeioCampo2)
                            .addComponent(btnZagueiro2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnVolante)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnPontEsq)
                                .addGap(142, 142, 142)
                                .addComponent(btnAtacante3))
                            .addComponent(btnGoleiro))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPontDir)
                    .addComponent(btnLatDir))
                .addGap(57, 57, 57))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPontEsq, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPontDir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtacante3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMeioCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMeioCampo2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(btnVolante, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLatEsq, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLatDir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(151, 151, 151))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnZagueiro1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnZagueiro2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76)
                        .addComponent(btnGoleiro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(810, 688));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPontEsqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPontEsqActionPerformed
                
        pontaDirEsq ponta = new pontaDirEsq();
        ponta.setVisible(true);     
                        
    }//GEN-LAST:event_btnPontEsqActionPerformed

    private void btnPontDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPontDirActionPerformed
       
        pontaDirEsq ponta = new pontaDirEsq();
        ponta.setVisible(true); 
        
    }//GEN-LAST:event_btnPontDirActionPerformed

    private void btnMeioCampo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMeioCampo1ActionPerformed
        
        meioCampo meio = new meioCampo();
        meio.setVisible(true);
        
    }//GEN-LAST:event_btnMeioCampo1ActionPerformed

    private void btnAtacante3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtacante3ActionPerformed

        atacante tela = new atacante();
        tela.setVisible(true);
       
    }//GEN-LAST:event_btnAtacante3ActionPerformed

    private void btnVolanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolanteActionPerformed
       
        volante volante = new volante();
        volante.setVisible(true);
        
    }//GEN-LAST:event_btnVolanteActionPerformed

    private void btnGoleiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoleiroActionPerformed

        goleiro goleiro = new goleiro();
        goleiro.setVisible(true);
       
    }//GEN-LAST:event_btnGoleiroActionPerformed

    private void btnAtacante6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtacante6ActionPerformed
        // DESATIVADO
        // DESATIVADO
    }//GEN-LAST:event_btnAtacante6ActionPerformed

    private void btnLatEsqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLatEsqActionPerformed
        
        LateralDirEsq lateral = new LateralDirEsq();
        lateral.setVisible(true);
        
    }//GEN-LAST:event_btnLatEsqActionPerformed

    private void btnLatDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLatDirActionPerformed
        
        LateralDirEsq lateral = new LateralDirEsq();
        lateral.setVisible(true);
        
    }//GEN-LAST:event_btnLatDirActionPerformed

    private void btnZagueiro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZagueiro1ActionPerformed
        
        zagueiro zagueiro = new zagueiro();
        zagueiro.setVisible(true);
        
    }//GEN-LAST:event_btnZagueiro1ActionPerformed

    private void btnZagueiro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZagueiro2ActionPerformed
        
        zagueiro zagueiro = new zagueiro();
        zagueiro.setVisible(true);
        
    }//GEN-LAST:event_btnZagueiro2ActionPerformed

    private void btnMeioCampo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMeioCampo2ActionPerformed
        
        meioCampo meio = new meioCampo();
        meio.setVisible(true);
        
    }//GEN-LAST:event_btnMeioCampo2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(selectionPosition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(selectionPosition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(selectionPosition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(selectionPosition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                
                new selectionPosition().setVisible(true);
            }
                        
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtacante3;
    private javax.swing.JButton btnAtacante6;
    private javax.swing.JButton btnGoleiro;
    private javax.swing.JButton btnLatDir;
    private javax.swing.JButton btnLatEsq;
    private javax.swing.JButton btnMeioCampo1;
    private javax.swing.JButton btnMeioCampo2;
    private javax.swing.JButton btnPontDir;
    private javax.swing.JButton btnPontEsq;
    private javax.swing.JButton btnVolante;
    private javax.swing.JButton btnZagueiro1;
    private javax.swing.JButton btnZagueiro2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlbChoose;
    // End of variables declaration//GEN-END:variables
}
