/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import Calculos.Calculos;
import data.CadastroDao;
import data.Jogador;
import javax.swing.JOptionPane;

public class Volante extends javax.swing.JFrame {

    Calculos calc = new Calculos();
    
    public Volante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtMedia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        txtNumCamisa = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        txtNome = new javax.swing.JTextField();
        btnMedia = new javax.swing.JButton();
        btnLimpFormulario = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        txtPasse = new javax.swing.JTextField();
        txtDefesa = new javax.swing.JTextField();
        txtRitmo = new javax.swing.JTextField();
        txtFinalizacao = new javax.swing.JTextField();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        txtCobrPenalti = new javax.swing.JTextField();
        txtCobrFalta = new javax.swing.JTextField();
        txtDrible = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Volante");

        jLabel3.setText("Nº da Camisa");

        jLabel12.setText("Pontuação");

        txtMedia.setEditable(false);
        txtMedia.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel4.setText("Nome");

        btnVoltar.setBackground(new java.awt.Color(255, 153, 153));
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        btnVoltar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnVoltarKeyPressed(evt);
            }
        });

        txtNumCamisa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumCamisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumCamisaKeyTyped(evt);
            }
        });

        btnSalvar.setBackground(new java.awt.Color(153, 255, 153));
        btnSalvar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        btnMedia.setBackground(new java.awt.Color(204, 204, 204));
        btnMedia.setText("Mostra Pontuação");
        btnMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMediaActionPerformed(evt);
            }
        });

        btnLimpFormulario.setBackground(new java.awt.Color(153, 204, 255));
        btnLimpFormulario.setText("Limpar Formulário");
        btnLimpFormulario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpFormularioActionPerformed(evt);
            }
        });

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel58.setText("Ritmo");

        jLabel59.setText("Finalização");

        jLabel60.setText("Defesa");

        jLabel61.setText("Passe");

        txtPasse.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPasse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasseActionPerformed(evt);
            }
        });
        txtPasse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPasseKeyTyped(evt);
            }
        });

        txtDefesa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDefesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDefesaActionPerformed(evt);
            }
        });
        txtDefesa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDefesaKeyTyped(evt);
            }
        });

        txtRitmo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtRitmo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRitmoActionPerformed(evt);
            }
        });
        txtRitmo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRitmoKeyTyped(evt);
            }
        });

        txtFinalizacao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFinalizacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFinalizacaoActionPerformed(evt);
            }
        });
        txtFinalizacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFinalizacaoKeyTyped(evt);
            }
        });

        jLabel62.setText("Drible");

        jLabel63.setText("Falta");

        jLabel64.setText("Penalti");

        txtCobrPenalti.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCobrPenalti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCobrPenaltiActionPerformed(evt);
            }
        });
        txtCobrPenalti.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCobrPenaltiKeyTyped(evt);
            }
        });

        txtCobrFalta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCobrFalta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCobrFaltaActionPerformed(evt);
            }
        });
        txtCobrFalta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCobrFaltaKeyTyped(evt);
            }
        });

        txtDrible.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDrible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDribleActionPerformed(evt);
            }
        });
        txtDrible.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDribleKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addComponent(jLabel64, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtCobrPenalti, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel62, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtDrible, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel63, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtCobrFalta, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtDefesa, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel61, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtPasse, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtRitmo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                            .addComponent(jLabel59, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtFinalizacao, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRitmo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFinalizacao, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel59, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDefesa, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPasse, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel61, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDrible, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel62, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCobrFalta, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel63, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCobrPenalti, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel64, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNumCamisa, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnLimpFormulario)
                                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(32, 32, 32)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVoltar)
                        .addGap(200, 200, 200)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNumCamisa, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(102, 102, 102)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnLimpFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(709, 544));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        new positionSelector().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
Jogador jogador;
    jogador = new Jogador();
    jogador.setNome(txtNome.getText());
    jogador.setNumcamisa(Double.parseDouble(txtNumCamisa.getText()));
    jogador.setRitmo(Double.parseDouble(txtRitmo.getText()));
    jogador.setFinalizacao(Double.parseDouble(txtFinalizacao.getText()));
    jogador.setDefesa(Double.parseDouble(txtDefesa.getText()));
    jogador.setPasse(Double.parseDouble(txtPasse.getText()));
    jogador.setDrible(Double.parseDouble(txtDrible.getText()));
    jogador.setCobrFalta(Double.parseDouble(txtCobrFalta.getText()));
    jogador.setCobrPenalti(Double.parseDouble(txtCobrPenalti.getText()));
    jogador.setPosicao("Volante");
    
    CadastroDao dao;
        dao = new CadastroDao();
        boolean status = dao.conectar();
        if(status==false){
            JOptionPane.showMessageDialog(null,"Erro na conexão");
        }
        else {
          int resposta =  dao.salvarJogador(jogador);
          if (resposta==1){
              JOptionPane.showMessageDialog(null,"Salvo com sucesso");
          
          }
          else{
              JOptionPane.showMessageDialog(null,"Erro na gravação. COntate o administrador do sistema");
          }
        }
    
    
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btnMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMediaActionPerformed

         if(txtRitmo.getText().isEmpty()){
          txtRitmo.setText("0");
      }if(txtPasse.getText().isEmpty()){
          txtPasse.setText("0");
      }if(txtDefesa.getText().isEmpty()){
          txtDefesa.setText("0");
      }if(txtCobrFalta.getText().isEmpty()){
          txtCobrFalta.setText("0");
      }if(txtCobrPenalti.getText().isEmpty()){
          txtCobrPenalti.setText("0");
      }if(txtDrible.getText().isEmpty()){
          txtDrible.setText("0");
      }if(txtFinalizacao.getText().isEmpty()){
          txtFinalizacao.setText("0");
      }
        calc.setDrible(Byte.parseByte(txtDrible.getText()));
        calc.setCobrFalta(Byte.parseByte(txtCobrFalta.getText()));
        calc.setCobrPenalti(Byte.parseByte(txtCobrPenalti.getText()));
        calc.setFinalizacao(Byte.parseByte(txtFinalizacao.getText()));
        calc.setRitmo(Byte.parseByte(txtRitmo.getText()));
        calc.setDefesa(Byte.parseByte(txtDefesa.getText()));
        calc.setPasse(Byte.parseByte(txtPasse.getText()));
        calc.volante(Float.parseFloat(txtRitmo.getText()), Float.parseFloat(txtDrible.getText()), Float.parseFloat(txtFinalizacao.getText()), Float.parseFloat(txtDefesa.getText()), Float.parseFloat(txtPasse.getText()), Float.parseFloat(txtCobrPenalti.getText()), Float.parseFloat(txtCobrFalta.getText()));
        txtMedia.setText(calc.getMedia());
    }//GEN-LAST:event_btnMediaActionPerformed

    private void btnLimpFormularioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpFormularioActionPerformed
      txtNome.setText("");
      txtNumCamisa.setText("");
      txtRitmo.setText("");
      txtFinalizacao.setText("");
      txtDefesa.setText("");
      txtPasse.setText("");
      txtDrible.setText("");
      txtCobrFalta.setText("");
      txtCobrPenalti.setText("");
      txtMedia.setText("");
    }//GEN-LAST:event_btnLimpFormularioActionPerformed

    private void txtPasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasseActionPerformed

    private void txtDefesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDefesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDefesaActionPerformed

    private void txtRitmoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRitmoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRitmoActionPerformed

    private void txtFinalizacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFinalizacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFinalizacaoActionPerformed

    private void txtCobrPenaltiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCobrPenaltiActionPerformed
        // TODO add your handling code here:
         if(txtRitmo.getText().isEmpty()){
          txtRitmo.setText("0");
      }if(txtPasse.getText().isEmpty()){
          txtPasse.setText("0");
      }if(txtDefesa.getText().isEmpty()){
          txtDefesa.setText("0");
      }if(txtCobrFalta.getText().isEmpty()){
          txtCobrFalta.setText("0");
      }if(txtCobrPenalti.getText().isEmpty()){
          txtCobrPenalti.setText("0");
      }if(txtDrible.getText().isEmpty()){
          txtDrible.setText("0");
      }if(txtFinalizacao.getText().isEmpty()){
          txtFinalizacao.setText("0");
      }
        calc.setDrible(Byte.parseByte(txtDrible.getText()));
        calc.setCobrFalta(Byte.parseByte(txtCobrFalta.getText()));
        calc.setCobrPenalti(Byte.parseByte(txtCobrPenalti.getText()));
        calc.setFinalizacao(Byte.parseByte(txtFinalizacao.getText()));
        calc.setRitmo(Byte.parseByte(txtRitmo.getText()));
        calc.setDefesa(Byte.parseByte(txtDefesa.getText()));
        calc.setPasse(Byte.parseByte(txtPasse.getText()));
        calc.lateralDirEsq(Float.parseFloat(txtRitmo.getText()), Float.parseFloat(txtDrible.getText()), Float.parseFloat(txtFinalizacao.getText()), Float.parseFloat(txtDefesa.getText()), Float.parseFloat(txtPasse.getText()), Float.parseFloat(txtCobrPenalti.getText()), Float.parseFloat(txtCobrFalta.getText()));
        txtMedia.setText(calc.getMedia());
    }//GEN-LAST:event_txtCobrPenaltiActionPerformed

    private void txtCobrFaltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCobrFaltaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCobrFaltaActionPerformed

    private void txtDribleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDribleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDribleActionPerformed

    private void txtNumCamisaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumCamisaKeyTyped
        
        if (evt.getKeyChar() == evt.VK_BACK_SPACE || (evt.getKeyChar() == evt.VK_0)|| (evt.getKeyChar() == evt.VK_1)|| (evt.getKeyChar() == evt.VK_2) 
            || (evt.getKeyChar() == evt.VK_3)|| (evt.getKeyChar() == evt.VK_4)|| (evt.getKeyChar() == evt.VK_5)|| (evt.getKeyChar() == evt.VK_6)|| (evt.getKeyChar() == evt.VK_7)
            || (evt.getKeyChar() == evt.VK_8)|| (evt.getKeyChar() == evt.VK_9)||(evt.getKeyChar() == evt.VK_ENTER))
          {          
        
          }
        else
          {
            evt.consume();
          }
        int numero = 3;
        if(txtNumCamisa.getText().length()>=numero){
          evt.consume();
        }
    }//GEN-LAST:event_txtNumCamisaKeyTyped

    private void txtRitmoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRitmoKeyTyped
        
        if (evt.getKeyChar() == evt.VK_BACK_SPACE || (evt.getKeyChar() == evt.VK_0)|| (evt.getKeyChar() == evt.VK_1)|| (evt.getKeyChar() == evt.VK_2) 
            || (evt.getKeyChar() == evt.VK_3)|| (evt.getKeyChar() == evt.VK_4)|| (evt.getKeyChar() == evt.VK_5)|| (evt.getKeyChar() == evt.VK_6)|| (evt.getKeyChar() == evt.VK_7)
            || (evt.getKeyChar() == evt.VK_8)|| (evt.getKeyChar() == evt.VK_9)||(evt.getKeyChar() == evt.VK_ENTER))
          {          
        
          }
        else
          {
            evt.consume();
          }
        int numero = 2;
        if(txtRitmo.getText().length()>=numero){
          evt.consume();
        }
    }//GEN-LAST:event_txtRitmoKeyTyped

    private void txtFinalizacaoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFinalizacaoKeyTyped
       
        if (evt.getKeyChar() == evt.VK_BACK_SPACE || (evt.getKeyChar() == evt.VK_0)|| (evt.getKeyChar() == evt.VK_1)|| (evt.getKeyChar() == evt.VK_2) 
            || (evt.getKeyChar() == evt.VK_3)|| (evt.getKeyChar() == evt.VK_4)|| (evt.getKeyChar() == evt.VK_5)|| (evt.getKeyChar() == evt.VK_6)|| (evt.getKeyChar() == evt.VK_7)
            || (evt.getKeyChar() == evt.VK_8)|| (evt.getKeyChar() == evt.VK_9)||(evt.getKeyChar() == evt.VK_ENTER))
          {          
        
          }
        else
          {
            evt.consume();
          }
        int numero = 2;
        if(txtFinalizacao.getText().length()>=numero){
          evt.consume();
        }
    }//GEN-LAST:event_txtFinalizacaoKeyTyped

    private void txtDefesaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDefesaKeyTyped
        
        if (evt.getKeyChar() == evt.VK_BACK_SPACE || (evt.getKeyChar() == evt.VK_0)|| (evt.getKeyChar() == evt.VK_1)|| (evt.getKeyChar() == evt.VK_2) 
            || (evt.getKeyChar() == evt.VK_3)|| (evt.getKeyChar() == evt.VK_4)|| (evt.getKeyChar() == evt.VK_5)|| (evt.getKeyChar() == evt.VK_6)|| (evt.getKeyChar() == evt.VK_7)
            || (evt.getKeyChar() == evt.VK_8)|| (evt.getKeyChar() == evt.VK_9)||(evt.getKeyChar() == evt.VK_ENTER))
          {          
        
          }
        else
          {
            evt.consume();
          }
        int numero = 2;
        if(txtDefesa.getText().length()>=numero){
          evt.consume();
        }
    }//GEN-LAST:event_txtDefesaKeyTyped

    private void txtPasseKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasseKeyTyped
        
        if (evt.getKeyChar() == evt.VK_BACK_SPACE || (evt.getKeyChar() == evt.VK_0)|| (evt.getKeyChar() == evt.VK_1)|| (evt.getKeyChar() == evt.VK_2) 
            || (evt.getKeyChar() == evt.VK_3)|| (evt.getKeyChar() == evt.VK_4)|| (evt.getKeyChar() == evt.VK_5)|| (evt.getKeyChar() == evt.VK_6)|| (evt.getKeyChar() == evt.VK_7)
            || (evt.getKeyChar() == evt.VK_8)|| (evt.getKeyChar() == evt.VK_9)||(evt.getKeyChar() == evt.VK_ENTER))
          {          
        
          }
        else
          {
            evt.consume();
          }
        int numero = 2;
        if(txtPasse.getText().length()>=numero){
          evt.consume();
        }
    }//GEN-LAST:event_txtPasseKeyTyped

    private void txtDribleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDribleKeyTyped
        
        if (evt.getKeyChar() == evt.VK_BACK_SPACE || (evt.getKeyChar() == evt.VK_0)|| (evt.getKeyChar() == evt.VK_1)|| (evt.getKeyChar() == evt.VK_2) 
            || (evt.getKeyChar() == evt.VK_3)|| (evt.getKeyChar() == evt.VK_4)|| (evt.getKeyChar() == evt.VK_5)|| (evt.getKeyChar() == evt.VK_6)|| (evt.getKeyChar() == evt.VK_7)
            || (evt.getKeyChar() == evt.VK_8)|| (evt.getKeyChar() == evt.VK_9)||(evt.getKeyChar() == evt.VK_ENTER))
          {          
        
          }
        else
          {
            evt.consume();
          }
        int numero = 2;
        if(txtDrible.getText().length()>=numero){
          evt.consume();
        }
    }//GEN-LAST:event_txtDribleKeyTyped

    private void txtCobrFaltaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCobrFaltaKeyTyped
        
        if (evt.getKeyChar() == evt.VK_BACK_SPACE || (evt.getKeyChar() == evt.VK_0)|| (evt.getKeyChar() == evt.VK_1)|| (evt.getKeyChar() == evt.VK_2) 
            || (evt.getKeyChar() == evt.VK_3)|| (evt.getKeyChar() == evt.VK_4)|| (evt.getKeyChar() == evt.VK_5)|| (evt.getKeyChar() == evt.VK_6)|| (evt.getKeyChar() == evt.VK_7)
            || (evt.getKeyChar() == evt.VK_8)|| (evt.getKeyChar() == evt.VK_9)||(evt.getKeyChar() == evt.VK_ENTER))
          {          
        
          }
        else
          {
            evt.consume();
          }
        int numero = 2;
        if(txtCobrFalta.getText().length()>=numero){
          evt.consume();
        }
    }//GEN-LAST:event_txtCobrFaltaKeyTyped

    private void txtCobrPenaltiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCobrPenaltiKeyTyped
        
        if (evt.getKeyChar() == evt.VK_BACK_SPACE || (evt.getKeyChar() == evt.VK_0)|| (evt.getKeyChar() == evt.VK_1)|| (evt.getKeyChar() == evt.VK_2) 
            || (evt.getKeyChar() == evt.VK_3)|| (evt.getKeyChar() == evt.VK_4)|| (evt.getKeyChar() == evt.VK_5)|| (evt.getKeyChar() == evt.VK_6)|| (evt.getKeyChar() == evt.VK_7)
            || (evt.getKeyChar() == evt.VK_8)|| (evt.getKeyChar() == evt.VK_9)||(evt.getKeyChar() == evt.VK_ENTER))
          {          
        
          }
        else
          {
            evt.consume();
          }
        int numero = 2;
        if(txtCobrPenalti.getText().length()>=numero){
          evt.consume();
        }
    }//GEN-LAST:event_txtCobrPenaltiKeyTyped

    private void btnVoltarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnVoltarKeyPressed
        // TODO add your handling code here:
        new positionSelector().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Volante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Volante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Volante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Volante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Volante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpFormulario;
    private javax.swing.JButton btnMedia;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField txtCobrFalta;
    private javax.swing.JTextField txtCobrPenalti;
    private javax.swing.JTextField txtDefesa;
    private javax.swing.JTextField txtDrible;
    private javax.swing.JTextField txtFinalizacao;
    private javax.swing.JTextField txtMedia;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumCamisa;
    private javax.swing.JTextField txtPasse;
    private javax.swing.JTextField txtRitmo;
    // End of variables declaration//GEN-END:variables
}
